 
# .github/workflows/ci.yml
# Continuous Integration: Run linters and tests on every pull request.

name: CI - Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint with Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Add your backend tests here if you have them, e.g., pytest
      # - name: Run Pytest
      #   run: pytest

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test