# Dockerfile.prefect
# Dockerfile for the Prefect Pipeline Worker

FROM python:3.9-slim-buster

WORKDIR /app

# Copy requirements for Prefect worker and pipeline dependencies
COPY requirements_prefect.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements_prefect.txt

# Command to start the Prefect worker
CMD ["prefect", "worker", "start", "--pool", "default-docker-pool", "--type", "docker"]
