version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fraudradar-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: fraudradar-frontend
    restart: unless-stopped
    ports:
      - "8501:8501" # Exposing for direct access if needed, but NGINX is the main entry point.
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: fraudradar-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend