# Dockerfile.mlflow
# Dockerfile for the MLflow Tracking Server

FROM python:3.9-slim-buster

WORKDIR /app

# Copy requirements for MLflow server
COPY requirements_mlflow.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements_mlflow.txt

# Command to run the MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "$(DATABASE_URL)", "--default-artifact-root", "s3://$(MLFLOW_ARTIFACT_BUCKET_NAME)/mlruns/"]
