  - type: web
    name: fraudradar-frontend
    env: docker
    dockerfilePath: ./app/frontend/Dockerfile
    dockerContext: . # ✅ Must be the root of your repo so COPY . . works properly
    envVars:
      - key: PORT
        value: 80
      - key: REACT_APP_BACKEND_HOST
        fromService:
          type: web
          name: fraudradar-backend
          property: host
      - key: REACT_APP_BACKEND_PORT
        fromService:
          type: web
          name: fraudradar-backend
          property: port
    plan: free
    healthCheckPath: /
